---
apiVersion: v1
kind: Pod
metadata:
  name: coco-demo-01
  namespace: default
  annotations:
    io.containerd.cri.runtime-handler: "kata-qemu-coco-dev"
spec:
  runtimeClassName: kata-qemu-coco-dev
  containers:
    - name: busybox
      image: busybox:stable-uclibc
      imagePullPolicy: Always
      command:
        - sleep
        - "infinity"
  restartPolicy: Never
...