---
apiVersion: v1
kind: Pod
metadata:
  name: coco-demo-06
  namespace: default
  annotations:
    io.containerd.cri.runtime-handler: "kata-qemu-coco-dev"
    io.katacontainers.config.hypervisor.kernel_params: " agent.aa_kbc_params=cc_kbc::http://${KBS_HOST}:${KBS_PORT}"
spec:
  runtimeClassName: kata-qemu-coco-dev
  containers:
    - name: busybox
      image: busybox:stable-uclibc
      imagePullPolicy: Always
      command:
        - sh
        - -c
        - |
          env | grep PROTECTED_SECRET
          sleep infinity
      env:
      - name: PROTECTED_SECRET
        valueFrom:
          secretKeyRef:
            name: sealed-secret
            key: secret
      volumeMounts:
        - name: sealed-secret-volume
          mountPath: "/sealed/secret-value"
  volumes:
    - name: sealed-secret-volume
      secret:
        secretName: sealed-secret
...