apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaim
metadata:
 name: rc-dra-gpu
 namespace: coco-dra
spec:
   devices:
     requests:
     - name: dra-gpu
       exactly:
         deviceClassName: gpu.dra-example.com
