---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: coco-test
nodes:
- role: control-plane
  image: kindest/node:v1.33.4@sha256:25a6018e48dfcaee478f4a59af81157a437f15e6e140bf103f85a2e7cd0cbbf2
  labels: 
    node.kubernetes.io/worker: ""
...